[theme]
base = "light"  # or "light" for light mode
primaryColor = "##46f207"    # Vibrant purple-blue for buttons/accent
backgroundColor = "#311847" # Deep navy background
secondaryBackgroundColor = "#1E293B" # Slightly lighter navy for widgets
textColor = "#F8FAFC"       # Crisp white text
font = "sans serif"         # Modern font stack

 

[client]
toolbarMode = "minimal"